env.client-id=MyMNQU-awjBR1-p8cIOC-DcjtxB
env.client-secret=ubytISxmvdsmig5R2IwygZHJG9NxbJtu99GNSfhM4MpNivgLrL
env.auth-server.url=http://auth-server.local:8080

env.logging.level.org.springframework.security=TRACE
env.logging.level.org.springframework.security.oauth2=TRACE