spring.application.name=test-oauth2-client
server.port=8082

server.servlet.session.cookie.name=CLIENT_SESSION

client-id=${env.client-id}
client-secret=${env.client-secret}
auth-server.url=${env.auth-server.url}

spring.security.oauth2.client.registration.auth-server.client-id=${client-id}
spring.security.oauth2.client.registration.auth-server.client-secret=${client-secret}

spring.security.oauth2.client.registration.auth-server.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth-server.client-authentication-method=client_secret_basic

spring.security.oauth2.client.registration.auth-server.scope[0]=openid
spring.security.oauth2.client.registration.auth-server.scope[1]=trs:produit-api.read

spring.security.oauth2.client.registration.auth-server.redirect-uri={baseUrl}/login/oauth2/code/auth-server

spring.security.oauth2.client.provider.auth-server.issuer-uri=${auth-server.url}

logging.level.org.springframework.security=${env.logging.level.org.springframework.security:INFO}
logging.level.org.springframework.security.oauth2=${env.logging.level.org.springframework.security.oauth2:INFO}